### ISSUE TITLE
Some ci-services are missing.

### ISSUE THREAD

**Issue by Nenglish7** [akbarhashmi/Secure-PHP-Login-System#1]
- Travis-CI
- Coveralls

**Comment by Nenglish7** [comment]
If you could goto https://coveralls.io/ and add this repo and i will create a pull request to make it work. Same goes with https://travis-ci.org/.

**Comment by akbarhashmi** [comment]
Added to both
.travis.yml is needed

**Comment by Nenglish7** [comment]
Travis-CI and Coveralls are working perfectly.
