### ISSUE TITLE
Rename repository.

### ISSUE THREAD

**Issue by Nenglish7** [akbarhashmi/Secure-PHP-Login-System#2]
Change `Secure-PHP-Login-Sytem` to `Secure-PHP-Login-System`

**Comment by Nenglish7** [comment]
Hi I am looking to collaborate with you on this project a have I good idea
in mind on how to set this up.

**Comment by akbarhashmi** [comment]
Hello

Glad to know you're interested collaborating. I should let you know that
I've just started learning web development.

**Comment by Nenglish7** [comment]
I have a good idea on how to set up a base structure. I am really good with
security in PHP. I will make sure there are no security leaks. I always put
tons of comments in my code so other developers can modify the code. I can
show you how to setup CI services that will test your code. I just need to
know what login features should we add.

**Comment by akbarhashmi** [comment]
> I have a good idea on how to set up a base structure. I am really good with
> security in PHP.

That's fascinating to here, will go a long way

> I can show you how to setup CI services that will test your code.

Yes, we can start with that

> I just need to know what login features should we add.

I haven't thought it through yet but the basic features for now could be

   - in-line validation (validation for a strong password too)
   - mobile-friendly
   - some sort of captcha validation
   - secure encryption and transfer of data

Im open to any more suggestions you might have

**Comment by akbarhashmi** [comment]
Hey

Do you want me to override the index.php file already present?

**Comment by Nenglish7** [comment]
Yea

**Comment by akbarhashmi** [comment]
Sorry for replying late, I've unit tests now, but ill have more time from
next week.
I cannot merge directly so github asks me to proceed with the following

git checkout -b Nenglish7-patch-4 mastergit pull
https://github.com/Nenglish7/Secure-PHP-Login-Sytem.git patch-4

*Step 2:* Merge the changes and update on GitHub.

git checkout mastergit merge --no-ff Nenglish7-patch-4git push origin master


Is this okay?

**Comment by Nenglish7** [comment]
Yea that should be okay, and if you want i can help out with the issues and pull request section by giving write access to help fix bug/security leaks more quickly.

**Comment by akbarhashmi** [comment]
I've sent an invitation already, perhaps you missed it
