### ISSUE TITLE
Add project package on composer.

### ISSUE THREAD

**Issue by Nenglish7** [akbarhashmi/Secure-PHP-Login-System#21]
Visit `https://packagist.org/` and click submit and put `https://github.com/akbarhashmi/Secure-PHP-Login-System`.

This allows people to use our project.

**Comment by Nenglish7** [comment]
If there is any composer json errors let me know and I'll fix them.

**Comment by akbarhashmi** [comment]
Successfully tested

**Comment by Nenglish7** [comment]
Awesome
